"""create tablas aula, sesión, asistencia

Revision ID: 390e4819672f
Revises: c03f0b1c982b
Create Date: 2025-05-07 15:42:40.850658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390e4819672f'
down_revision: Union[str, None] = 'c03f0b1c982b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aula_id'), 'aula', ['id'], unique=False)
    op.create_table('alumnos_aulas',
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], ),
    sa.PrimaryKeyConstraint('alumno_id', 'aula_id')
    )
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clase_id'), 'clase', ['id'], unique=False)
    op.create_table('asistencia',
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['clase.id'], ),
    sa.PrimaryKeyConstraint('alumno_id', 'sesion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_clase_id'), table_name='clase')
    op.drop_table('clase')
    op.drop_table('alumnos_aulas')
    op.drop_index(op.f('ix_aula_id'), table_name='aula')
    op.drop_table('aula')
    # ### end Alembic commands ###
