"""aula add año division especialidad

Revision ID: 9e8a91852fcc
Revises: b5a404f6443e
Create Date: 2025-05-08 11:41:33.573651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8a91852fcc'
down_revision: Union[str, None] = 'b5a404f6443e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aula', sa.Column('ano', sa.Integer(), nullable=False))
    op.add_column('aula', sa.Column('division', sa.Integer(), nullable=False))
    op.add_column('aula', sa.Column('especialidad', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aula', 'especialidad')
    op.drop_column('aula', 'division')
    op.drop_column('aula', 'ano')
    # ### end Alembic commands ###
