"""agregar tablas

Revision ID: f1f346b5077c
Revises: 390e4819672f
Create Date: 2025-05-07 20:03:01.226928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f346b5077c'
down_revision: Union[str, None] = '390e4819672f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencia', sa.Column('clase_id', sa.Integer(), nullable=False))
    op.drop_constraint('asistencia_sesion_id_fkey', 'asistencia', type_='foreignkey')
    op.create_foreign_key(None, 'asistencia', 'clase', ['clase_id'], ['id'])
    op.drop_column('asistencia', 'sesion_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencia', sa.Column('sesion_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'asistencia', type_='foreignkey')
    op.create_foreign_key('asistencia_sesion_id_fkey', 'asistencia', 'clase', ['sesion_id'], ['id'])
    op.drop_column('asistencia', 'clase_id')
    # ### end Alembic commands ###
